### ISSUE TITLE
Add parameters to tag too like in SublimeText

### ISSUE THREAD

**Issue by alexbet** [sanusart/atom-wrap-in-tag#1]
This is a great package, but it would be much better if it worked just like in SublimeText. For example, if I wanted to add a class to the tag too, I keep on typing after the tag "div class...", right now, the text gets copied to the closing tag too. How it works in SublimeText is, when you hit space after the tag, what you type next is no longer being copied to the closing tag. Also, when you hit the Esc button, the cursor goes back to the starting tag, not the ending tag like in this package. 

Anyway, just my two cents. If you incorporate these things, this package will be much more useful. :)

**Comment by kswedberg** [comment]
Agreed. This would be _much_ more useful if it didn't copy attributes to closing tag.

**Comment by sanusart** [comment]
Agree, Thanks for suggestion.

**Comment by Paul-Hume** [comment]
This would be really handy :)

**Comment by sanusart** [comment]
Should be available in v0.5.0 FYI

**Comment by kswedberg** [comment]
thanks, @sanusart!
