### ISSUE TITLE
Alt-Shift-W applies multiple tags at once 

### ISSUE THREAD

**Issue by baskinco** [sanusart/atom-wrap-in-tag#10]
When selecting a block of text and entering Alt-Shift-W on the keyboard, multiple tags are applied at once. Im using Atom 1.14.4 and ato-wrap-in-tag version 0.6.0 on a Mac.
<img width="873" alt="screen shot 2017-03-14 at 8 31 21 am" src="https://cloud.githubusercontent.com/assets/24660966/23905505/e59f6ab6-0890-11e7-8752-08d5563dd8b4.png">

**Comment by sanusart** [comment]
Can you specify what was the selection please?

**Comment by baskinco** [comment]
"I want this all to be uppercase"

**Comment by sanusart** [comment]
It looks like the only way I can get into the situation in screenshot above, is by hitting Opt+Shift+w more than one time. Is that the case for you?

**Comment by baskinco** [comment]
No, i’m only hitting Opt+Shift+W one time. At first it was adding only 2 extra tags. Then I uninstalled, reinstalled the package, then it was 6 tags. 

I just uninstalled the package, restarted my computer again, reinstalled the package and now it seems to be working. 

No idea :)

Thanks for the quick response though!

Marc Baskin
Proprietor & Creative Director, Baskin & Company
www.baskin.co.com
mobile 403-689-6135


On March 14, 2017 at 3:19:23 PM, Sasha Khamkov (notifications@github.com) wrote:

It looks like the only way I can get into the situation in screenshot above, is by hitting Opt+Shift+w more than one time. Is that the case for you?

**Comment by sanusart** [comment]
Strange, it might also be somehow related to fast key repeat, but I am using the fastest too and all seem to be fine.

Anyway glad it resolved.

**Comment by AgustinLado** [comment]
Same thing happened to me. I suspected it might have been some compatibility issues with _double-tag_, but after reinstalling both packages (restarting Atom in between each step) the issue was fixed.

So the mystery continues, but for anyone reading this, restart Atom and/or reinstall the package.
