### ISSUE TITLE
Keybinding options

### ISSUE THREAD

**Issue by darylknight** [sanusart/atom-wrap-in-tag#5]
In Sublime, my keybinding for this was ctrl-shift-w, but I can't work out how to customise this package to do that. Is it possible?

**Comment by sanusart** [comment]
You should be able to add this to your `keymap.cson`:

```
'atom-workspace':
  'ctrl-shift-W': 'wrap-in-tag:wrap'
```

Jusr make sure nothing else is using this combination.

**Comment by darylknight** [comment]
Perfect, thank you. Although the solution was actually:

```
'atom-text-editor':
    'f5': 'editor:auto-indent'
    'ctrl-shift-W': 'wrap-in-tag:wrap'
```
