### ISSUE TITLE
Wrap in tag with different tag templates

### ISSUE THREAD

**Issue by mrniko** [sanusart/atom-wrap-in-tag#7]
Hi!

Cool project. 
It would be useful to introduce tag template in case if I want to tag with class. For example <p class="myclass">some text</p> or <span class="myclass">some text</span>
Also, it would be nice to add shortkeys for each tag template. For example:

Alt+Shift+1 wraps text into: <span class="myclass1">some text</span>
Alt+Shift+2 wraps text into: <div class="myclass2">some text</div>
and so on.

I think having 10 templates with shortkeys in settings would be enough.

**Comment by sanusart** [comment]
@mrniko Wouldn't it kind of defeat the purpose of this as a "wrap in tag"? 
But it is probably good idea for stand alone package.

**Comment by mrniko** [comment]
@sanusart Do you think my issue is out of scope of this project?

**Comment by sanusart** [comment]
@mrniko I mean this one is only addressing HTML tag wrapping, we got some text wrapping packages already for pretty similar functionality (e.g. https://atom.io/packages/wrap-selection). So I wonder if this feature you've mentioned above actually fits to be added into this one.
Or am I misunderstanding the first post?

**Comment by mrniko** [comment]
I think you're my request would probably good for wrap-selection project. Thank you!
