### ISSUE TITLE
escape	inline-autocomplete:cycle

### ISSUE THREAD

**Issue by brentgreeff** [sanusart/atom-wrap-in-tag#9]
After I enter a tag, lets say: &lt;span&gt; I want to press esc to cancel the double insertion points, but instead it autocompletes to content inside the document - changing the closing tag &lt;/spanner&gt;

- using the inline-autocomplete plugin, so that I get textmate like behaviour ( press esc to auto-complete from current doc )

**Comment by sanusart** [comment]
@brentgreeff Correct me if I am wrong, but isn't is kind of inline-autocomplete "fault" that it uses the most generic key to do it's magic?

I am not familiar with inline-autocomplete, but any suggestions will be welcomed.
